a, b, c= input().split()
x = (int(a)+int(b))%int(c)
y = (int(a)%int(c)+int(b)%int(c))%int(c)
z = (int(a)*int(b))%int(c)
w = ((int(a)%int(c))*(int(b)%int(c)))%int(c)
print(x)
print(y)
print(z)
print(w)